# Now we will create new Aplication Load Balancer Security Group
- name: Create ALB Security Group
  ec2_group:
    name: "My ALB SG"
    description: "My ALB Access"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "{{ my_ip }}/0"
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "{{ my_ip }}/0"
    tags:
      Name: "My Test SG"
  register: my_alb_sg

- name: Set ALB SG ID
  set_fact:
    alb_sg_id: "{{ my_alb_sg.group_id }}"

#- name: debug EC2 ids
#  debug:
#    msg: "{{ ec2.tagged_instances[0].id }}"

# Now we will create new Traget Group
- name: Create Traget Group for ALB
  elb_target_group:
    name: mytargetgroup
    region: "{{ aws_region }}"
    protocol: http
    vpc_id: "{{ vpc_id }}"
    port: 80
    health_check_path: /
    successful_response_codes: "200,250-260"
    state: present
    targets:
      - Id: "{{ ec2.tagged_instances[0].id }}"
        Port: 80
    wait_timeout: 200
  register: my_target_group

- name: Set Target Group Name
  set_fact:
    target_grp_name: "{{ my_target_group.target_group_name }}"

- name: Create ALB
  elb_application_lb:
    name: myalb
    region: "{{ aws_region }}"
    subnets:
      - "{{ public_subnet_az1_id }}"
      - "{{ public_subnet_az2_id }}"
    security_groups: "{{ alb_sg_id }}"
    scheme: internet-facing
    listeners:
      - Protocol: HTTPS 
        Port: 443 
        # The security policy that defines which ciphers and protocols are supported. The default is the current predefined security policy.
        SslPolicy: ELBSecurityPolicy-2015-05
        Certificates: # The ARN of the certificate (only one certficate ARN should be provided)
          - CertificateArn: "{{ ssl_arn }}"
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ target_grp_name }}"
      - Protocol: HTTP 
        Port: 80 
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ target_grp_name }}" 
    state: present
  register: my_alb

- name: debug ALB DNS
  debug:
    msg: "{{ my_alb.dns_name }}"


# Update EC2's Security Group to Add 80 and 443 rule to ALB SG

- name: Update Main Security Group to allow trafic to ALB SG 
  ec2_group:
    name: "External Access"
    description: "External Access"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "{{ my_ip }}/0"
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        group_id: "{{ alb_sg_id }}" 
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        group_id: "{{ alb_sg_id }}" 
      - proto: "tcp"
        from_port: "8080"
        to_port: "8080"
        cidr_ip: "{{ my_ip }}/0"
    tags:
      Name: "My Test SG"
