# Now Craete RED Hat EC2 Instance

- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ main_sg_id }}"
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"
    wait: true
    region: "{{ aws_region }}"
    exact_count: 1
    count_tag:
      Name: Demo
    instance_tags:
      Name: Demo
    vpc_subnet_id: "{{ public_subnet_az1_id }}"
    assign_public_ip: yes
  register: ec2

#- name:  Set EC2 Info in variable
#  set_fact:
#    ec2_info: "{{ ec2 }}"

# Update VPC's Security Group to Add 80 Port

- name: Update Main Security Group to allow Port
  ec2_group:
    name: "External Access"
    description: "External Access"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "{{ my_ip }}/0"
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "{{ my_ip }}/0"
    tags:
      Name: "My Test SG"
  register: my_main_sg

- name: Wait for the instances to boot by checking the ssh port
  wait_for: 
    host: "{{item.public_dns_name}}" 
    port: 22 
    delay: 60 
    timeout: 320 
    state: started
  with_items: "{{ ec2.tagged_instances }}"

- name: Add new instances to host group
  add_host:  hostname={{item.public_ip}} groupname=launched
  with_items: "{{ ec2.tagged_instances }}"

- name: Add EC2 instances as known hosts
  known_hosts:
    name: "{{ item.public_ip }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
  with_items: "{{ ec2.tagged_instances }}"
